#!/bin/bash

wallpaper=$(ls ~/Pictures/wallpapers | dmenu -fn "Hack:size=15" -nb "#2D121F" -nf "#FFFFFF" -sb "#B984E5" -sf "#FFD7FF" -l 10)

[ $wallpaper -z ] || feh --bg-fill /home/komi/Pictures/wallpapers/$wallpaper
